#<!-- feign:
#  client:
#    config:
#      default:
#        connectTimeout: 2500
#        readTimeout: 3000
#        loggerLevel: BASIC -->
logging:  level:    '[com.feign.demo.client.StudentCallFeignInterface]': debug
feign:
  client:
    config:
      studentCall:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: FULL
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#            - com.feign.demo.config.FeignClientConfig
#            - com.example.FooRequestInterceptor
##          - com.example.BarRequestInterceptor
        decode404: false
#        encoder: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract